### ISSUE TITLE
Build failure: initGC() not in scope

### ISSUE THREAD

**Issue by conklech** [NixOS/hydra#205]
$ nix-build release.nix -A build.x86_64-linux
    ...
    hydra-eval-jobs.cc: In lambda function:
    hydra-eval-jobs.cc:215:16: error: 'initGC' was not declared in this scope
             initGC();
                    ^

Presumably caused by 479632efa3a5f0d229cba41f4905dcbad9d083aa. Rolling back to 4c0e3e47034545ad3e9e86dd069138bcebb8ccee results in a successful build.

**Comment by aszlig** [comment]
This function has been introduced in NixOS/nix@726f7f7fc92f4914bca450a37b8b85b1018afc01, so you either need a newer version of Nix to build it or revert the change.

**Comment by conklech** [comment]
Understood. I'm on nixos unstable, which I guess doesn't include that
update. I guess this issue can be closed, but for a while longer it'll bite
people who follow the various instructions (e.g. [nixos wiki](
https://nixos.org/wiki/Installing_hydra_as_nixos_module)) to install Hydra
from git.

Out of curiosity, why is hydra not in nixpkgs?

**Comment by aszlig** [comment]
Not yet, but it will be included as nixUnstable after the channel update. As for the second question: Cc: @edolstra, @rbvermaa

**Comment by dantheho** [comment]
Ran into this using nixos channel for 14.12, so then I updated the root nixos nix-channel to 15.09 and it worked for 7b9f488

**Comment by domenkozar** [comment]
Closing as this is very old now.
